export type ToneName = 'neutral' | 'brand' | 'mint' | 'amber' | 'rose' | 'cyan' | 'dark' | 'violet';

/** Shared status → colour mapping, usable from both server and client components. */
export const stageTone = (stage: string): ToneName =>
  (({
    Applied: 'neutral',
    Screened: 'cyan',
    Shortlisted: 'brand',
    Interviewing: 'violet',
    Offered: 'amber',
    Hired: 'mint',
    Rejected: 'rose',
    Withdrawn: 'neutral',
    Open: 'mint',
    Draft: 'neutral',
    'Pending Approval': 'amber',
    'On Hold': 'amber',
    Closed: 'neutral',
    Scheduled: 'brand',
    Completed: 'mint',
    Cancelled: 'rose',
    'Awaiting Feedback': 'amber',
    Pending: 'amber',
    Approved: 'mint',
    Sent: 'brand',
    Accepted: 'mint',
    Declined: 'rose',
    Active: 'mint',
    Onboarding: 'cyan',
    'Notice Period': 'amber',
    Exited: 'neutral',
    'Not Started': 'neutral',
    'In Progress': 'brand',
    Blocked: 'rose',
    High: 'rose',
    Medium: 'amber',
    Low: 'mint',
    Critical: 'rose',
    Modified: 'brand',
    'Info Requested': 'cyan',
    Finalised: 'mint',
  }) as Record<string, ToneName>)[stage] ?? 'neutral';
