import type { AgentDefinition } from '../types';

export const AGENTS: AgentDefinition[] = [
  {
    id: 'coordinator',
    name: 'HR Coordinator Agent',
    shortName: 'Coordinator',
    category: 'Orchestration',
    mission:
      'Interprets any HR request in natural language, decomposes it into a plan, routes work to specialist agents, holds task state, aggregates results and escalates every sensitive decision to a named human approver.',
    capabilities: [
      'Natural-language intent classification across 12 HR workflow families',
      'Multi-agent plan construction with dependency ordering',
      'Task state machine (Waiting → Processing → Completed / Needs Approval / Failed)',
      'Result aggregation and narrative synthesis',
      'Approval gate enforcement and audit-log emission',
    ],
    inputs: ['HR request text', 'Actor role', 'Organisational context'],
    outputs: ['Execution plan', 'Agent task graph', 'Aggregated result', 'Approval requests', 'Audit entries'],
    requiresApproval: false,
    guardrails: [
      'Never executes an employment decision itself',
      'Refuses plans that would auto-reject, auto-hire or auto-terminate',
      'Every run is written to the immutable audit log',
    ],
    icon: 'network',
  },
  {
    id: 'workforce-planning',
    name: 'Workforce Planning Agent',
    shortName: 'Workforce Planning',
    category: 'Talent Acquisition',
    mission:
      'Turns a business change or capacity signal into a defensible hiring plan: which roles, which skills, what seniority, what priority and why.',
    capabilities: [
      'Business-signal to role mapping',
      'Skill demand derivation',
      'Seniority and headcount recommendation',
      'Hiring justification and priority scoring',
      'Organisational skill-shortage detection from the live skill graph',
    ],
    inputs: ['Business initiative', 'Current headcount & skills', 'Attrition and workload signals'],
    outputs: ['Recommended roles', 'Required skills', 'Priority', 'Written justification'],
    requiresApproval: false,
    guardrails: ['Advisory only — headcount approval remains a human budget decision'],
    icon: 'compass',
  },
  {
    id: 'job-description',
    name: 'Job Description Agent',
    shortName: 'JD Agent',
    category: 'Talent Acquisition',
    mission:
      'Drafts a complete, inclusive, bias-checked job description with explicit weighted evaluation criteria that later drive candidate scoring.',
    capabilities: [
      'Structured JD generation (summary, responsibilities, skills, education, criteria)',
      'Inclusive-language checking',
      'Weighted evaluation-criteria design',
      'Salary-band and seniority consistency checks',
    ],
    inputs: ['Role', 'Location', 'Department', 'Seniority', 'Skills', 'Experience'],
    outputs: ['Editable job description draft', 'Evaluation criteria with weights'],
    requiresApproval: true,
    guardrails: [
      'Draft is never published without human approval',
      'Flags exclusionary or gender-coded phrasing before submission',
    ],
    icon: 'file-text',
  },
  {
    id: 'email-intake',
    name: 'Email Intake Agent',
    shortName: 'Email Intake',
    category: 'Talent Acquisition',
    mission:
      'The first stage of candidate acquisition. Watches the recruitment mailboxes, detects genuine applications, extracts the CV securely and starts the intake pipeline — turning an inbox into structured, screened applications with no recruiter keystrokes.',
    capabilities: [
      'Mailbox monitoring across Microsoft Graph, Gmail and IMAP',
      'Sender, subject and body extraction',
      'Résumé attachment detection and secure extraction',
      'Downstream agent orchestration',
      'Application acknowledgement dispatch',
      'Full audit trail per message',
    ],
    inputs: ['Recruitment mailbox message', 'Attachments', 'Open requisitions'],
    outputs: ['Incoming email record', 'Validated attachment', 'Triggered intake pipeline', 'Acknowledgement'],
    requiresApproval: false,
    guardrails: [
      'Mailbox credentials live only in server-side environment variables',
      'Least-privilege, read-only mailbox scopes (plus Send only when acknowledgements are enabled)',
      'Acknowledgement wording confirms receipt only and never implies shortlisting',
      'Simulated messages run the identical pipeline — there is no separate demo path',
    ],
    icon: 'inbox',
  },
  {
    id: 'document-processing',
    name: 'Document Processing Agent',
    shortName: 'Document Processing',
    category: 'Talent Acquisition',
    mission:
      'Treats every inbound attachment as untrusted. Validates type, signature, size and content shape, quarantines anything suspicious, and extracts text without ever executing the file.',
    capabilities: [
      'Extension, MIME type and magic-number verification',
      'File-size ceiling and double-extension detection',
      'Executable and archive blocking with quarantine',
      'Résumé-content heuristics',
      'SHA-256 content hashing for deduplication and audit',
      'Safe text extraction from PDF, DOC and DOCX',
    ],
    inputs: ['Email attachment', 'Declared MIME type', 'File bytes'],
    outputs: ['Validation report', 'Extracted text', 'Content hash', 'Quarantine decision'],
    requiresApproval: false,
    guardrails: [
      'Uploaded files are never executed',
      'Declared MIME type is never trusted without a signature check',
      'Suspicious files are quarantined, not parsed',
    ],
    icon: 'file-check',
  },
  {
    id: 'resume-parsing',
    name: 'Résumé Parsing Agent',
    shortName: 'Résumé Parsing',
    category: 'Talent Acquisition',
    mission:
      'Converts a CV into a structured, comparable candidate profile — identity, experience, skills, certifications, education, projects and availability — with a confidence score on the extraction itself.',
    capabilities: [
      'Section-aware extraction across 18 résumé fields',
      'Skill normalisation against the governed taxonomy',
      'Employment history and tenure derivation',
      'Notice period and stated salary capture',
      'LinkedIn and portfolio URL detection',
      'Extraction-confidence scoring',
    ],
    inputs: ['Extracted résumé text', 'Skill taxonomy'],
    outputs: ['Structured résumé record', 'Normalised skills', 'Extraction confidence'],
    requiresApproval: false,
    guardrails: [
      'Never extracts or infers gender, age, race, religion, nationality, marital status or disability',
      'Reports what it could not find rather than filling gaps with inference',
    ],
    icon: 'file-search',
  },
  {
    id: 'candidate-profile',
    name: 'Candidate Profile Agent',
    shortName: 'Candidate Profile',
    category: 'Talent Acquisition',
    mission:
      'Maintains one profile per person. Detects returning applicants across five signals and links a new application to the existing record instead of fragmenting the candidate history.',
    capabilities: [
      'Deduplication on email, phone, résumé hash, name and application history',
      'Candidate profile creation from parsed résumé data',
      'Profile refresh from newer résumé versions without losing history',
      'One candidate, many applications',
    ],
    inputs: ['Parsed résumé', 'Sender identity', 'Existing candidate records'],
    outputs: ['Candidate profile', 'Job application record', 'Duplicate signals'],
    requiresApproval: false,
    guardrails: ['Never merges two people on a weak signal alone; every match signal is shown to the recruiter'],
    icon: 'user-check',
  },
  {
    id: 'job-matching',
    name: 'Job Matching Agent',
    shortName: 'Job Matching',
    category: 'Talent Acquisition',
    mission:
      'Determines which vacancy an application is for, in a fixed priority order — stated intent first, inference last — and refuses to guess when confidence is low.',
    capabilities: [
      'Requisition-code detection in subject and body',
      'Job-title detection in subject and body',
      'Skills, experience, location and certification inference',
      'Primary match with confidence plus ranked alternatives',
      'Low-confidence routing to Unassigned Applications',
    ],
    inputs: ['Email subject and body', 'Parsed résumé', 'Open requisitions'],
    outputs: ['Primary job match with confidence', 'Alternative matches', 'Match explanation'],
    requiresApproval: false,
    guardrails: [
      "A candidate's explicitly stated role always takes priority over inference",
      'Below the confidence threshold the agent assigns nothing and asks a recruiter',
    ],
    icon: 'git-compare',
  },
  {
    id: 'talent-acquisition',
    name: 'Talent Acquisition Agent',
    shortName: 'Talent Acquisition',
    category: 'Talent Acquisition',
    mission:
      'Owns requisitions and the candidate pipeline: parses CVs, extracts structured skills and experience, and builds comparable candidate profiles.',
    capabilities: [
      'Resume parsing into a structured profile',
      'Skill and certification extraction with years-of-use',
      'Pipeline stage management',
      'Talent-pool matching across open requisitions',
    ],
    inputs: ['Resumes', 'Application data', 'Open requisitions'],
    outputs: ['Structured candidate profiles', 'Pipeline updates'],
    requiresApproval: false,
    guardrails: ['Stores only job-relevant attributes; protected attributes are dropped at parse time'],
    icon: 'users',
  },
  {
    id: 'screening',
    name: 'AI Resume Screening Agent',
    shortName: 'Screening',
    category: 'Talent Acquisition',
    mission:
      'Scores every candidate against the approved job description using the same weighted criteria, and explains each component of the score with evidence.',
    capabilities: [
      'Weighted multi-dimension match scoring',
      'Matched vs missing requirement analysis',
      'Strength, concern and interview-focus generation',
      'Full score explainability with evidence per dimension',
    ],
    inputs: ['Approved job description', 'Candidate profile'],
    outputs: ['Match score', 'Score breakdown', 'Strengths', 'Gaps', 'Interview focus areas'],
    requiresApproval: true,
    guardrails: [
      'Cannot reject a candidate — produces recommendations only',
      'Gender, race, religion, nationality, disability, marital status and age are excluded from every dimension',
      'Every score ships with its evidence trail',
    ],
    icon: 'scan-search',
  },
  {
    id: 'interview-intelligence',
    name: 'Interview Intelligence Agent',
    shortName: 'Interview Questions',
    category: 'Talent Acquisition',
    mission:
      'Generates a tailored, structured interview guide from the job description and the specific candidate profile, targeting evidenced strengths and identified gaps.',
    capabilities: [
      'Per-candidate question generation across six categories',
      'Gap-targeted probing questions',
      'Scenario design calibrated to claimed years of experience',
      '"What good looks like" guidance for each question',
    ],
    inputs: ['Job description', 'Candidate profile', 'Screening gaps'],
    outputs: ['Interview guide', 'Evaluation rubric hints'],
    requiresApproval: false,
    guardrails: ['Never generates questions touching protected attributes or personal circumstances'],
    icon: 'message-square',
  },
  {
    id: 'interview-evaluation',
    name: 'Interview Evaluation Agent',
    shortName: 'Interview Evaluation',
    category: 'Talent Acquisition',
    mission:
      'Synthesises interviewer ratings and notes into a structured, comparable evaluation with a reasoned recommendation — which a human then accepts, modifies or overrides.',
    capabilities: [
      'Rating normalisation across interviewers',
      'Narrative summary generation',
      'Recommendation with explicit reasoning',
      'Panel consistency and divergence detection',
    ],
    inputs: ['Interviewer ratings', 'Interview notes', 'Role bar'],
    outputs: ['Evaluation summary', 'Recommendation', 'Reasoning'],
    requiresApproval: true,
    guardrails: ['Hiring decision authority stays with the hiring manager'],
    icon: 'clipboard-check',
  },
  {
    id: 'scheduling',
    name: 'Interview Scheduling Agent',
    shortName: 'Scheduling',
    category: 'Talent Acquisition',
    mission:
      'Finds workable interview slots against interviewer availability, books the meeting and keeps candidate status in sync.',
    capabilities: [
      'Availability resolution across interviewers',
      'Slot suggestion with timezone handling',
      'Invitation dispatch (simulated in prototype)',
      'Candidate stage synchronisation',
    ],
    inputs: ['Shortlisted candidate', 'Interviewer', 'Round type'],
    outputs: ['Proposed slots', 'Booked interview', 'Invitation'],
    requiresApproval: false,
    guardrails: ['Calendar integrations are simulated in the prototype; no external invites are sent'],
    icon: 'calendar',
  },
  {
    id: 'offer-onboarding',
    name: 'Offer & Onboarding Agent',
    shortName: 'Offer & Onboarding',
    category: 'Talent Acquisition',
    mission:
      'Drafts the offer, then converts an accepted offer into a fully sequenced onboarding programme across HR, IT, compliance and the hiring manager.',
    capabilities: [
      'Offer letter drafting within the approved band',
      'Document and verification checklist generation',
      'Day −7 to Day 30 onboarding schedule',
      'IT access, asset and orientation task assignment',
    ],
    inputs: ['Hiring approval', 'Role and band', 'Department onboarding template'],
    outputs: ['Offer draft', 'Onboarding plan', 'Assigned tasks'],
    requiresApproval: true,
    guardrails: ['Offers are never issued without a named human approver'],
    icon: 'briefcase',
  },
  {
    id: 'helpdesk',
    name: 'HR Helpdesk Agent',
    shortName: 'HR Helpdesk',
    category: 'Employee Experience',
    mission:
      'Answers employee HR questions from the governed policy knowledge base using retrieval-augmented generation, always citing the source policy and version.',
    capabilities: [
      'Retrieval over the HR policy knowledge base',
      'Grounded answer generation with citations',
      'Personal-entitlement lookup (balances, probation dates)',
      'Escalation to a human HR partner when confidence is low',
    ],
    inputs: ['Employee question', 'Policy corpus', 'Employee record'],
    outputs: ['Grounded answer', 'Policy citation', 'Suggested next action'],
    requiresApproval: false,
    guardrails: [
      'Never answers outside retrieved policy content',
      'Escalates rather than speculating when no policy matches',
    ],
    icon: 'life-buoy',
  },
  {
    id: 'leave',
    name: 'Leave Management Agent',
    shortName: 'Leave',
    category: 'Employee Experience',
    mission:
      'Converts a plain-language leave request into a validated, conflict-checked request routed to the correct approver.',
    capabilities: [
      'Date and leave-type extraction from natural language',
      'Working-day calculation excluding weekends',
      'Balance validation and team-coverage conflict detection',
      'Approver resolution and routing',
    ],
    inputs: ['Employee request', 'Leave balances', 'Team calendar'],
    outputs: ['Leave request', 'Conflict report', 'Approval routing'],
    requiresApproval: true,
    guardrails: ['Approval remains with the line manager; the agent never self-approves'],
    icon: 'calendar-days',
  },
  {
    id: 'performance',
    name: 'Performance Management Agent',
    shortName: 'Performance',
    category: 'Workforce Intelligence',
    mission:
      'Prepares evidence-based review packs for managers: goal attainment, strengths, development areas and next-cycle objectives.',
    capabilities: [
      'Goal attainment analysis',
      'Evidence aggregation across goals, training and feedback',
      'Structured summary generation',
      'Next-quarter objective suggestion',
    ],
    inputs: ['Goals', 'Completed work', 'Feedback', 'Training records'],
    outputs: ['Performance summary', 'Suggested objectives', 'Draft rating for review'],
    requiresApproval: true,
    guardrails: ['Ratings are advisory; the manager sets and HR approves the final rating'],
    icon: 'target',
  },
  {
    id: 'learning',
    name: 'Learning & Skills Agent',
    shortName: 'Learning',
    category: 'Workforce Intelligence',
    mission:
      'Maintains the live skill graph, computes the distance between an employee and a target role, and builds a sequenced personal learning roadmap.',
    capabilities: [
      'Skill-profile maintenance',
      'Target-role gap analysis',
      'Course, certification, lab, mentoring and internal-project matching',
      'Phased roadmap generation',
    ],
    inputs: ['Employee skill profile', 'Target role requirements', 'Course catalogue'],
    outputs: ['Skill gaps', 'Learning roadmap', 'Recommended interventions'],
    requiresApproval: false,
    guardrails: ['Recommendations are developmental and never used as a basis for adverse action'],
    icon: 'graduation-cap',
  },
  {
    id: 'engagement',
    name: 'Employee Engagement Agent',
    shortName: 'Engagement',
    category: 'Workforce Intelligence',
    mission:
      'Reads anonymised feedback at aggregate level and surfaces the themes moving organisational sentiment, without ever re-identifying an individual.',
    capabilities: [
      'Theme extraction across seven engagement dimensions',
      'Sentiment trending by quarter and department',
      'Emerging-issue detection',
      'Suggested management actions',
    ],
    inputs: ['Anonymised feedback', 'Engagement survey scores'],
    outputs: ['Theme analysis', 'Sentiment trend', 'Recommended actions'],
    requiresApproval: false,
    guardrails: [
      'Aggregates only; suppresses any segment with fewer than 5 responses',
      'Protected attributes are never used as an analysis dimension',
    ],
    icon: 'heart-pulse',
  },
  {
    id: 'retention',
    name: 'Retention Risk Agent',
    shortName: 'Retention Risk',
    category: 'Workforce Intelligence',
    mission:
      'Flags where the organisation is likely to lose capability, using only explainable, work-related indicators — as an input to a human retention conversation.',
    capabilities: [
      'Explainable risk scoring from six work-related indicators',
      'Contributing-factor attribution',
      'Department and team-level roll-up',
      'Suggested supportive interventions',
    ],
    inputs: ['Engagement trend', 'Performance history', 'Tenure', 'Training participation', 'Internal mobility', 'Workload index'],
    outputs: ['Risk level', 'Contributing factors', 'Suggested supportive actions'],
    requiresApproval: false,
    guardrails: [
      'Never recommends termination, demotion or any adverse employment action',
      'Uses no protected attributes; every factor is displayed to the user',
      'Output supports HR analysis only and is access-restricted to HR roles',
    ],
    icon: 'shield-alert',
  },
  {
    id: 'offboarding',
    name: 'Offboarding Agent',
    shortName: 'Offboarding',
    category: 'Employee Experience',
    mission:
      'Runs a clean, auditable exit: interview, assets, access revocation, knowledge transfer, payroll and documentation, with live completion tracking.',
    capabilities: [
      'Exit checklist generation',
      'Cross-functional task assignment',
      'Access-revocation tracking',
      'Knowledge-transfer verification',
      'Completion percentage reporting',
    ],
    inputs: ['Resignation record', 'Role and assets', 'Notice period'],
    outputs: ['Offboarding plan', 'Task status', 'Completion percentage'],
    requiresApproval: false,
    guardrails: ['Access revocation actions are logged and require IT confirmation'],
    icon: 'log-out',
  },
];

export const agentById = (id: string) => AGENTS.find((a) => a.id === id);
export const agentName = (id: string) => agentById(id)?.name ?? id;
